#!/usr/bin/env bash

set -o errexit

make=(make -j 8)
# make=(make)

# set variables

# xml_catalog=../../distro/niem/xml-catalog.xml
xml_catalog_file=inputs/person-subset/niem/xml-catalog.xml
build_dir=build

# other variables

prefixes_file=${build_dir}/prefixes.xml
backlinks_file=${build_dir}/backlinks.xml

# actions

rm -rf ${build_dir}
mkdir -p ${build_dir}

echo "# collect prefixes"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/collect-prefixes.xsl \
      --out=${prefixes_file}

echo "# generate makefile definitions"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/generate-makefile.xsl \
      --out=build/definitions.mk \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file}

echo "# collect backlinks"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/collect-backlinks.xsl \
      --out=${backlinks_file} \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file}

# make directories
"${make[@]}" -f generate.mk dirs

echo "# run generate mode=component-diagram"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/generate.xsl \
      --out=${build_dir}/report.txt \
      -- -im:"{}component-diagram" \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file} \
      +backlinks-file=${backlinks_file} \
      root-path=$PWD/${build_dir}

echo "# make diagrams"

"${make[@]}" -f generate.mk diagrams

echo "# run generate"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/generate.xsl \
      --out=${build_dir}/report.txt \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file} \
      +backlinks-file=${backlinks_file} \
      root-path=$PWD/${build_dir}

rm -rf ../repo/*

"${make[@]}" -f generate.mk install install_dir=../repo




