#!/usr/bin/env bash

set -o errexit

# set variables

# xml_catalog=../../distro/niem/xml-catalog.xml
xml_catalog=inputs/person-subset/niem/xml-catalog.xml
build_dir=build

# other variables

prefixes_file=${build_dir}/prefixes.xml

# actions

rm -rf ${build_dir}
mkdir -p ${build_dir}

echo "# collect prefixes"

saxon --in=${xml_catalog} \
      --xsl=xsl/collect-prefixes.xsl \
      --out=${prefixes_file}

echo "# generate pre"

saxon --in=${xml_catalog} \
      --xsl=xsl/generate-pre.xsl \
      --out=${build_dir}/pre.bash \
      +prefixes-file=${prefixes_file}

echo "# run pre"

( cd ${build_dir} && bash ./pre.bash )

echo "# run generate"

saxon --in=${xml_catalog} \
      --xsl=xsl/generate.xsl \
      --out=${build_dir}/report.txt \
      +prefixes-file=${prefixes_file} \
      root-path=$PWD/${build_dir}



