#!/usr/bin/env bash

set -o errexit

# set variables

# xml_catalog=../../distro/niem/xml-catalog.xml
xml_catalog_file=inputs/person-subset/niem/xml-catalog.xml
build_dir=build

# other variables

prefixes_file=${build_dir}/prefixes.xml
backlinks_file=${build_dir}/backlinks.xml

# actions

rm -rf ${build_dir}
mkdir -p ${build_dir}

echo "# collect prefixes"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/collect-prefixes.xsl \
      --out=${prefixes_file}

echo "# collect backlinks"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/collect-backlinks.xsl \
      --out=${backlinks_file} \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file}

echo "# generate pre"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/generate-pre.xsl \
      --out=${build_dir}/pre.bash \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file}

echo "# run pre"

( cd ${build_dir} && bash ./pre.bash )

echo "# run generate mode=component-diagram"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/generate.xsl \
      --out=${build_dir}/report.txt \
      -- -im:"{}component-diagram" \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file} \
      root-path=$PWD/${build_dir}

make dot

echo "# run generate"

saxon --in=${xml_catalog_file} \
      --xsl=xsl/generate.xsl \
      --out=${build_dir}/report.txt \
      +prefixes-file=${prefixes_file} \
      +xml-catalog-file=${xml_catalog_file} \
      root-path=$PWD/${build_dir}



