
* Strategy:

1. One prefix per namespace.
2. Only reference schemas (for now) & profiles of reference schemas.
3. URI for a component looks like:

   ${root}/${prefix}/${component-local-name}

4. Each component is a single page. What we put on each page is TBD, as much detail as is useful, but no more.
5. Each page is a folder containing an index.md
6. Everything in Markdown, with images as PNGs via Graphviz.
7. Graphviz images use maps for hotlinks to other component pages.
8. Use Makefiles dependencies to build everything in parallel without rebuilding everything every time.
9. Every anchor needs to be semantically-based, not built with generate-id(), to be consistent across builds.

* Someday Maybe items:

1. Include in the source dir, or another dir, a set of pages that augment the documentation for a given component. This could be a pile of markdown and images that is somehow integrated with the generated pages. This might include, for example, specific examples of use of a component. That would be in a page within the hierarchy for the component, with a given name.
2. Provide sample JSON schema for a component as it appears in the XML schema.

* Graph conventions
** Lists
- e.g., lists of elements, lists of types, etc.
- order
  - structures
  - nc
  - everything else, in alphabetical order
** Cardinality examples

- 1 
- 0-1
- 0-n
- 1-n
- 2-n
- 3-5
- 4-n

* Resources

- see ~/working/test-gen-xsd-diagrams/
- see /Users/wr/r/by-topic/graphviz/graphics-nc-PersonType.gv
