#!/usr/bin/env bash

. "$HOME"/share/wrtools-core/fail.bash

(( $# > 0 )) || fail "need a command"

command=$1
shift 1

case $command in
    rebuild )
        rm -rf build
        make depend=true
        make "$@"
        ;;
    release )
        rm -rf build
        rm -rf .../repo/*
        ./configure install_dir=../repo xml_catalog=../../niem-releases/niem/xml-catalog.xml
        make depend=true
        make -k -j -l 50
        make -k -j -l 50 install
        date
        ;;
    backlinks )
        rm -f build/backlinks.xml
        make build/backlinks.xml
        ;;
    show )
        remove=(rm -rf)
        build=(make -j 8)
        for path in "$@"
        do remove+=( "build/$path" )
           build+=( "build/$path/index.html" )
        done
        "${remove[@]}"
        "${build[@]}"
        if (( $# > 0 ))
        then open "${build[3]}"
        fi
        ;;
    * )
        fail "unknown command $1"
        ;;
esac
